import React from "react";
import { Image } from "react-native";

const ICONS = {
  add: require("../assets/icons8/add.png"),
  alarm: require("../assets/icons8/alarm.png"),
  approval: require("../assets/icons8/approval.png"),
  "appointment-reminders": require("../assets/icons8/appointment-reminders.png"),
  back: require("../assets/icons8/back.png"),
  bookmark: require("../assets/icons8/bookmark.png"),
  business: require("../assets/icons8/business.png"),
  calendar: require("../assets/icons8/calendar.png"),
  camera: require("../assets/icons8/camera.png"),
  cash: require("../assets/icons8/cash.png"),
  chat: require("../assets/icons8/chat.png"),
  checkmark: require("../assets/icons8/checkmark.png"),
  "chevron-down": require("../assets/icons8/chevron-down.png"),
  clipboard: require("../assets/icons8/clipboard.png"),
  "cloud-checked": require("../assets/icons8/cloud-checked.png"),
  "cloud-cross": require("../assets/icons8/cloud-cross.png"),
  "combo-chart": require("../assets/icons8/combo-chart.png"),
  compare: require("../assets/icons8/compare.png"),
  "delete-sign": require("../assets/icons8/delete-sign.png"),
  diamond: require("../assets/icons8/diamond.png"),
  document: require("../assets/icons8/document.png"),
  "double-tick": require("../assets/icons8/double-tick.png"),
  dumbbell: require("../assets/icons8/dumbbell.png"),
  ellipse: require("../assets/icons8/ellipse.png"),
  exchange: require("../assets/icons8/exchange.png"),
  exit: require("../assets/icons8/exit.png"),
  "external-link": require("../assets/icons8/external-link.png"),
  "fire-element": require("../assets/icons8/fire-element.png"),
  flag: require("../assets/icons8/flag.png"),
  football: require("../assets/icons8/football.png"),
  forward: require("../assets/icons8/forward.png"),
  globe: require("../assets/icons8/globe.png"),
  hand: require("../assets/icons8/hand.png"),
  help: require("../assets/icons8/help.png"),
  hide: require("../assets/icons8/hide.png"),
  "high-priority": require("../assets/icons8/high-priority.png"),
  home: require("../assets/icons8/home.png"),
  hourglass: require("../assets/icons8/hourglass.png"),
  information: require("../assets/icons8/information.png"),
  leaderboard: require("../assets/icons8/leaderboard.png"),
  leaf: require("../assets/icons8/leaf.png"),
  left: require("../assets/icons8/left.png"),
  like: require("../assets/icons8/like.png"),
  "lightning-bolt": require("../assets/icons8/lightning-bolt.png"),
  link: require("../assets/icons8/link.png"),
  list: require("../assets/icons8/list.png"),
  lock: require("../assets/icons8/lock.png"),
  map: require("../assets/icons8/map.png"),
  marker: require("../assets/icons8/marker.png"),
  medal: require("../assets/icons8/medal.png"),
  "medical-doctor": require("../assets/icons8/medical-doctor.png"),
  megaphone: require("../assets/icons8/megaphone.png"),
  "merge-git": require("../assets/icons8/merge-git.png"),
  microphone: require("../assets/icons8/microphone.png"),
  minus: require("../assets/icons8/minus.png"),
  more: require("../assets/icons8/more.png"),
  navigation: require("../assets/icons8/navigation.png"),
  news: require("../assets/icons8/news.png"),
  "no-entry": require("../assets/icons8/no-entry.png"),
  "no-reminders": require("../assets/icons8/no-reminders.png"),
  "open-envelope": require("../assets/icons8/open-envelope.png"),
  options: require("../assets/icons8/options.png"),
  planet: require("../assets/icons8/planet.png"),
  play: require("../assets/icons8/play.png"),
  private: require("../assets/icons8/private.png"),
  prize: require("../assets/icons8/prize.png"),
  "radio-button": require("../assets/icons8/radio-button.png"),
  receipt: require("../assets/icons8/receipt.png"),
  repeat: require("../assets/icons8/repeat.png"),
  right: require("../assets/icons8/right.png"),
  rocket: require("../assets/icons8/rocket.png"),
  save: require("../assets/icons8/save.png"),
  school: require("../assets/icons8/school.png"),
  search: require("../assets/icons8/search.png"),
  send: require("../assets/icons8/send.png"),
  settings: require("../assets/icons8/settings.png"),
  share: require("../assets/icons8/share.png"),
  shield: require("../assets/icons8/shield.png"),
  "sort": require("../assets/icons8/sort.png"),
  sparkles: require("../assets/icons8/sparkles.png"),
  "speech-bubble": require("../assets/icons8/speech-bubble.png"),
  square: require("../assets/icons8/square.png"),
  "stack-of-photos": require("../assets/icons8/stack-of-photos.png"),
  star: require("../assets/icons8/star.png"),
  "t-shirt": require("../assets/icons8/t-shirt.png"),
  ticket: require("../assets/icons8/ticket.png"),
  time: require("../assets/icons8/time.png"),
  trash: require("../assets/icons8/trash.png"),
  trophy: require("../assets/icons8/trophy.png"),
  tv: require("../assets/icons8/tv.png"),
  user: require("../assets/icons8/user.png"),
  "user-group-man-man": require("../assets/icons8/user-group-man-man.png"),
  "add-user-male": require("../assets/icons8/add-user-male.png"),
  "video-call": require("../assets/icons8/video-call.png"),
  visible: require("../assets/icons8/visible.png"),
  walking: require("../assets/icons8/walking.png"),
  wallet: require("../assets/icons8/wallet.png"),
};

export const APP_ICON_ASSETS = Object.values(ICONS);

const ALIASES = {
  alert: "high-priority",
  analytics: "combo-chart",
  "arrow-back": "left",
  "arrow-forward": "right",
  ban: "no-entry",
  card: "ticket",
  chatbubble: "speech-bubble",
  chatbubbles: "chat",
  "checkmark-done": "double-tick",
  "chevron-back": "back",
  "chevron-forward": "forward",
  close: "delete-sign",
  "cloud-done": "cloud-checked",
  "cloud-offline": "cloud-cross",
  "document-lock": "private",
  "document-text": "document",
  earth: "globe",
  "ellipsis-horizontal": "more",
  eye: "visible",
  "eye-off": "hide",
  fitness: "dumbbell",
  flame: "fire-element",
  flash: "lightning-bolt",
  "git-compare": "compare",
  "git-merge": "merge-git",
  "hand-left": "hand",
  heart: "like",
  images: "stack-of-photos",
  location: "marker",
  "lock-closed": "lock",
  "log-out": "exit",
  "mail-open": "open-envelope",
  medkit: "medical-doctor",
  mic: "microphone",
  navigate: "navigation",
  newspaper: "news",
  notifications: "appointment-reminders",
  "notifications-off": "no-reminders",
  open: "external-link",
  people: "user-group-man-man",
  person: "user",
  "person-add": "add-user-male",
  podium: "leaderboard",
  radio: "radio-button",
  remove: "minus",
  ribbon: "prize",
  "share-social": "share",
  "shield-checkmark": "approval",
  shirt: "t-shirt",
  "stats-chart": "combo-chart",
  "swap-horizontal": "exchange",
  "swap-vertical": "sort",
  videocam: "video-call",
  walk: "walking",
};

const baseName = (name = "") =>
  name.replace(/-outline$/, "").replace(/-circle$/, "");

export default function AppIcon({
  name,
  size = 24,
  color = "#17131D",
  style,
  ...props
}) {
  const base = baseName(name);
  const key = ALIASES[base] || base;
  const source = ICONS[key] || ICONS.help;

  return (
    <Image
      {...props}
      accessible={false}
      resizeMode="contain"
      source={source}
      style={[
        {
          width: size,
          height: size,
          tintColor: color,
        },
        style,
      ]}
    />
  );
}
